version: "2.4"

networks:
  cassandra:

services:
  cassandra1:
    image: cassandra:3.11.8   # better to use a specific version, if you want to control upgrades
    container_name: cassandra1
    hostname: cassandra1
    mem_limit: 512m  # It's not strictly required, but it's better to have some memory limit
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9042:9042"  # Expose native binary CQL port for your apps
    environment: &environment    # Declare and save environments variables into "environment"
        CASSANDRA_SEEDS: "cassandra1,cassandra2"    # The first two nodes will be seeds
        CASSANDRA_CLUSTER_NAME: SolarSystem
        CASSANDRA_DC: Mars
        CASSANDRA_RACK: West
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 128
        MAX_HEAP_SIZE: 512M
        HEAP_NEWSIZE: 128M

  cassandra2:
    image: cassandra:3.11.8
    container_name: cassandra2
    hostname: cassandra2
    mem_limit: 512m
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9043:9042"  # Expose native binary CQL port for your apps
    environment: *environment    # point to "environment" to use the same environment variables as cass1
    depends_on:
      cassandra1:    # start cass2 only after cass1 is healthy
        condition: service_healthy

  cassandra3:
    image: cassandra:3.11.8
    container_name: cassandra3
    hostname: cassandra3
    mem_limit: 512m
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9044:9042"  # Expose native binary CQL port for your apps
    environment: *environment    # point to "environment" to use the same environment variables as cass1
    depends_on:
      cassandra2:    # start cass2 only after cass1 is healthy
        condition: service_healthy

  netcorecassandra:
    build:
      context: CassandraConsole/.
      dockerfile: Dockerfile
    container_name: netcorecassandra
    mem_limit: 128m
    networks:
      - cassandra
    expose:
      - 80
    ports:
      - 9080:80
      - 9081:443
    depends_on:
      - cassandra3